package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.22

import (
	"context"

	"github.com/ducdang91/go-gqlgen-dataloader/graph/model"

	"github.com/ducdang91/go-gqlgen-dataloader/service"
)

// Summary is the resolver for the summary field.
func (r *transactionResolver) Summary(ctx context.Context, obj *model.Transaction) (*model.TransactionSummary, error) {
	return service.TransactionDetailGetSummaryByTransactionID(ctx, obj.ID)
}

// Create is the resolver for the create field.
func (r *transactionOpsResolver) Create(ctx context.Context, obj *model.TransactionOps, input model.NewTransaction) (*model.Transaction, error) {
	return service.TransactionCreate(ctx, input)
}

// Transaction returns TransactionResolver implementation.
func (r *Resolver) Transaction() TransactionResolver { return &transactionResolver{r} }

// TransactionOps returns TransactionOpsResolver implementation.
func (r *Resolver) TransactionOps() TransactionOpsResolver { return &transactionOpsResolver{r} }

type transactionResolver struct{ *Resolver }
type transactionOpsResolver struct{ *Resolver }
