// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewTransaction struct {
	UserID             int                     `json:"user_id"`
	TransactionDetails []*NewTransactionDetail `json:"transaction_details"`
}

type NewTransactionDetail struct {
	Name        string   `json:"name"`
	Description *string  `json:"description"`
	Price       float64  `json:"price"`
	Discount    *float64 `json:"discount"`
}

type NewUser struct {
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type TransactionOps struct {
	Create *Transaction `json:"create"`
}

type TransactionSummary struct {
	TotalPrice         float64              `json:"total_price"`
	TotalDiscount      *float64             `json:"total_discount"`
	TransactionDetails []*TransactionDetail `json:"transaction_details"`
}

type UserOps struct {
	Create *User `json:"create"`
}
